import {
  TriggerType,
  ConditionOperator,
  AIActionType,
  SystemActionType,
  AutomationTemplate,
} from './automation-types';

export const TRIGGER_OPTIONS: Array<{ value: TriggerType; label: string; description: string; category: string }> = [
  { value: 'SCHEDULE', label: 'Schedule / Cron', description: 'Triggers on periodic intervals or daily/weekly schedules', category: 'Time' },
  { value: 'CALENDAR_EVENT', label: 'Calendar Event', description: 'Triggers before or after a calendar meeting or event', category: 'Events' },
  { value: 'TASK_CREATED', label: 'Task Created', description: 'Triggers when a new task is added to workspace', category: 'Tasks' },
  { value: 'TASK_COMPLETED', label: 'Task Completed', description: 'Triggers when any task is marked done', category: 'Tasks' },
  { value: 'TASK_OVERDUE', label: 'Task Overdue', description: 'Triggers when a task deadline passes', category: 'Tasks' },
  { value: 'PROJECT_CREATED', label: 'Project Created', description: 'Triggers when a project is initialized', category: 'Projects' },
  { value: 'PROJECT_UPDATED', label: 'Project Updated', description: 'Triggers when project status or milestones change', category: 'Projects' },
  { value: 'GOAL_UPDATED', label: 'Goal Progress Updated', description: 'Triggers when key results or goal metrics update', category: 'Goals' },
  { value: 'DOCUMENT_CREATED', label: 'Document Created', description: 'Triggers when a document or note is created in Knowledge', category: 'Knowledge' },
  { value: 'DOCUMENT_UPDATED', label: 'Document Updated', description: 'Triggers when a document is updated', category: 'Knowledge' },
  { value: 'FILE_UPLOADED', label: 'File Uploaded', description: 'Triggers when a file is uploaded to workspace', category: 'Files' },
  { value: 'AI_EVENT', label: 'AI Event / Signal', description: 'Triggers when Aether AI detects high priority context', category: 'AI' },
  { value: 'AGENT_EVENT', label: 'Agent Signal', description: 'Triggers when a background agent finishes execution', category: 'AI' },
  { value: 'MANUAL', label: 'Manual Trigger', description: 'Triggers on user click or quick shortcut', category: 'General' },
];

export const CONDITION_OPERATORS: Array<{ value: ConditionOperator; label: string }> = [
  { value: 'equals', label: 'Equals' },
  { value: 'not_equals', label: 'Does Not Equal' },
  { value: 'contains', label: 'Contains' },
  { value: 'exists', label: 'Exists / Not Null' },
  { value: 'is_empty', label: 'Is Empty' },
  { value: 'greater_than', label: 'Greater Than' },
  { value: 'less_than', label: 'Less Than' },
  { value: 'AND', label: 'AND' },
  { value: 'OR', label: 'OR' },
  { value: 'NOT', label: 'NOT' },
];

export const AI_ACTION_OPTIONS: Array<{ value: AIActionType; label: string; description: string }> = [
  { value: 'ASK_AETHER', label: 'Ask Aether AI', description: 'Query Aether with custom system instructions' },
  { value: 'SUMMARIZE', label: 'Summarize Content', description: 'Generate concise executive summary of input' },
  { value: 'ANALYZE', label: 'Analyze Priorities', description: 'Evaluate urgency, task load, and dependencies' },
  { value: 'CLASSIFY', label: 'Classify & Tag', description: 'Categorize document, task, or message into tags' },
  { value: 'GENERATE', label: 'Generate Action Plan', description: 'Draft step-by-step resolution plan' },
  { value: 'EXTRACT', label: 'Extract Entities', description: 'Pull key dates, contacts, and action items' },
  { value: 'TRANSFORM', label: 'Transform Format', description: 'Convert text to markdown, JSON, or task structure' },
];

export const SYSTEM_ACTION_OPTIONS: Array<{ value: SystemActionType; label: string; description: string }> = [
  { value: 'CREATE_TASK', label: 'Create Task', description: 'Add a new task to workspace with assignee & due date' },
  { value: 'UPDATE_TASK', label: 'Update Task', description: 'Change status, priority, or tags of a task' },
  { value: 'COMPLETE_TASK', label: 'Complete Task', description: 'Mark matching tasks as completed' },
  { value: 'CREATE_PROJECT', label: 'Create Project', description: 'Initialize a new project board' },
  { value: 'UPDATE_PROJECT', label: 'Update Project', description: 'Modify project progress or status' },
  { value: 'UPDATE_GOAL', label: 'Update Goal Progress', description: 'Record progress on active goal' },
  { value: 'CREATE_CALENDAR_EVENT', label: 'Create Calendar Event', description: 'Schedule event or block focus time in Calendar' },
  { value: 'CREATE_REMINDER', label: 'Create Reminder', description: 'Set timed notification reminder' },
  { value: 'CREATE_KNOWLEDGE_ITEM', label: 'Create Knowledge Note', description: 'Save AI response or digest to Knowledge base' },
  { value: 'SAVE_AI_RESPONSE', label: 'Save AI Response', description: 'Log AI output into project notes' },
  { value: 'ORGANIZE_DOCUMENT', label: 'Organize Document', description: 'Tag and move document to knowledge category' },
  { value: 'ORGANIZE_FILE', label: 'Organize File', description: 'Categorize uploaded file into project directory' },
  { value: 'RUN_SUPPORTED_AGENT', label: 'Run Autonomous Agent', description: 'Invoke specialized background AI agent' },
  { value: 'CREATE_NOTIFICATION', label: 'Send Notification', description: 'Alert user via in-app notifications' },
];

export const AUTOMATION_TEMPLATES: AutomationTemplate[] = [
  {
    id: 'tmpl-daily-planning',
    title: 'Daily Planning Briefing',
    description: 'Every weekday morning, Aether reviews your calendar & tasks, synthesizes priorities, and prepares your daily action plan.',
    category: 'Productivity',
    badge: 'Popular',
    iconName: 'Calendar',
    popularity: 98,
    estimatedTimeSaved: '2.5 hrs / week',
    preset: {
      name: 'Daily Planning Briefing',
      description: 'Reviews calendar & open tasks every morning at 8:00 AM',
      trigger: 'SCHEDULE',
      schedule: '0 8 * * 1-5',
      steps: [
        {
          id: 'step-1',
          type: 'trigger',
          title: 'Schedule: Weekdays at 8:00 AM',
          triggerType: 'SCHEDULE',
          config: { cron: '0 8 * * 1-5' },
        },
        {
          id: 'step-2',
          type: 'ai_action',
          title: 'Analyze Calendar & Task Priorities',
          aiActionType: 'ANALYZE',
          config: { scope: ['calendar', 'tasks'], goal: 'Identify top 3 focus priorities' },
        },
        {
          id: 'step-3',
          type: 'action',
          title: 'Generate Notification Briefing',
          actionType: 'CREATE_NOTIFICATION',
          config: { title: 'Your Aether Daily Plan is Ready' },
        },
      ],
    },
  },
  {
    id: 'tmpl-morning-briefing',
    title: 'Morning Executive Briefing',
    description: 'Scans overdue items, critical milestones, and unread notifications to present a morning executive digest.',
    category: 'Productivity',
    badge: 'Essential',
    iconName: 'Sparkles',
    popularity: 92,
    estimatedTimeSaved: '1.5 hrs / week',
    preset: {
      name: 'Morning Executive Briefing',
      description: 'Collects key updates every day at 7:30 AM',
      trigger: 'SCHEDULE',
      schedule: '30 7 * * *',
      steps: [
        {
          id: 'step-1',
          type: 'trigger',
          title: 'Schedule: Everyday at 7:30 AM',
          triggerType: 'SCHEDULE',
          config: { cron: '30 7 * * *' },
        },
        {
          id: 'step-2',
          type: 'ai_action',
          title: 'Summarize Workspace Health',
          aiActionType: 'SUMMARIZE',
          config: { includeOverdue: true, includeProjects: true },
        },
        {
          id: 'step-3',
          type: 'action',
          title: 'Create Knowledge Note',
          actionType: 'CREATE_KNOWLEDGE_ITEM',
          config: { title: 'Executive Briefing' },
        },
      ],
    },
  },
  {
    id: 'tmpl-task-deadline-monitor',
    title: 'Task Deadline Sentinel',
    description: 'Monitors overdue and high-priority tasks, auto-elevating flags and notifying assignees.',
    category: 'Productivity',
    badge: 'Automation',
    iconName: 'Clock',
    popularity: 88,
    estimatedTimeSaved: '2 hrs / week',
    preset: {
      name: 'Task Deadline Sentinel',
      description: 'Triggers when a task passes due date',
      trigger: 'TASK_OVERDUE',
      steps: [
        {
          id: 'step-1',
          type: 'trigger',
          title: 'Trigger: Task Overdue',
          triggerType: 'TASK_OVERDUE',
          config: {},
        },
        {
          id: 'step-2',
          type: 'condition',
          title: 'Check if High Priority',
          config: { operator: 'equals', field: 'priority', value: 'high' },
        },
        {
          id: 'step-3',
          type: 'action',
          title: 'Send High Priority Alert',
          actionType: 'CREATE_NOTIFICATION',
          config: { urgency: 'high' },
        },
      ],
    },
  },
  {
    id: 'tmpl-project-progress-review',
    title: 'Weekly Project Progress Audit',
    description: 'Calculates milestone progress across active projects every Friday afternoon and outputs a status digest.',
    category: 'Projects',
    badge: 'Reports',
    iconName: 'Folder',
    popularity: 85,
    estimatedTimeSaved: '3 hrs / week',
    preset: {
      name: 'Weekly Project Progress Audit',
      description: 'Audits project milestones every Friday at 4:00 PM',
      trigger: 'SCHEDULE',
      schedule: '0 16 * * 5',
      steps: [
        {
          id: 'step-1',
          type: 'trigger',
          title: 'Schedule: Fridays at 4:00 PM',
          triggerType: 'SCHEDULE',
          config: { cron: '0 16 * * 5' },
        },
        {
          id: 'step-2',
          type: 'ai_action',
          title: 'Evaluate Milestones & Progress',
          aiActionType: 'ANALYZE',
          config: { target: 'all_projects' },
        },
        {
          id: 'step-3',
          type: 'action',
          title: 'Update Goal Progress',
          actionType: 'UPDATE_GOAL',
          config: { autoSync: true },
        },
      ],
    },
  },
  {
    id: 'tmpl-doc-organizer',
    title: 'Knowledge Document Auto-Indexer',
    description: 'When new notes or document files are uploaded, Aether automatically categorizes, tags, and links them to relevant projects.',
    category: 'Knowledge',
    badge: 'AI Powered',
    iconName: 'BookOpen',
    popularity: 91,
    estimatedTimeSaved: '4 hrs / week',
    preset: {
      name: 'Knowledge Document Auto-Indexer',
      description: 'Triggers on file upload or document creation',
      trigger: 'FILE_UPLOADED',
      steps: [
        {
          id: 'step-1',
          type: 'trigger',
          title: 'Trigger: Document / File Added',
          triggerType: 'FILE_UPLOADED',
          config: {},
        },
        {
          id: 'step-2',
          type: 'ai_action',
          title: 'Classify & Tag Content',
          aiActionType: 'CLASSIFY',
          config: { autoTag: true },
        },
        {
          id: 'step-3',
          type: 'action',
          title: 'Organize into Knowledge Base',
          actionType: 'ORGANIZE_DOCUMENT',
          config: { autoLinkProject: true },
        },
      ],
    },
  },
  {
    id: 'tmpl-conv-to-task',
    title: 'AI Signal → Task Generator',
    description: 'Transforms high-level AI directives or meeting takeaways into actionable workspace tasks with due dates.',
    category: 'AI',
    badge: 'AI Native',
    iconName: 'Bot',
    popularity: 95,
    estimatedTimeSaved: '3.5 hrs / week',
    preset: {
      name: 'AI Signal → Task Generator',
      description: 'Triggers when AI assistant detects actionable items',
      trigger: 'AI_EVENT',
      steps: [
        {
          id: 'step-1',
          type: 'trigger',
          title: 'Trigger: AI Directive Event',
          triggerType: 'AI_EVENT',
          config: {},
        },
        {
          id: 'step-2',
          type: 'ai_action',
          title: 'Extract Tasks & Action Items',
          aiActionType: 'EXTRACT',
          config: { extractDueDates: true },
        },
        {
          id: 'step-3',
          type: 'action',
          title: 'Create Workspace Tasks',
          actionType: 'CREATE_TASK',
          config: { autoAssign: true },
        },
      ],
    },
  },
];
