/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as CognitiveLabIndexRouteImport } from './routes/cognitive-lab/index'
import { Route as CognitiveLabGameIdRouteImport } from './routes/cognitive-lab/$gameId'
import { Route as CognitiveLabDailyRouteImport } from './routes/cognitive-lab/daily'
import { Route as CognitiveLabDashboardRouteImport } from './routes/cognitive-lab/dashboard'
import { Route as ApiRagEmbedRouteImport } from './routes/api/rag/embed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitiveLabIndexRoute = CognitiveLabIndexRouteImport.update({
  id: '/cognitive-lab/',
  path: '/cognitive-lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitiveLabGameIdRoute = CognitiveLabGameIdRouteImport.update({
  id: '/cognitive-lab/$gameId',
  path: '/cognitive-lab/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitiveLabDailyRoute = CognitiveLabDailyRouteImport.update({
  id: '/cognitive-lab/daily',
  path: '/cognitive-lab/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitiveLabDashboardRoute = CognitiveLabDashboardRouteImport.update({
  id: '/cognitive-lab/dashboard',
  path: '/cognitive-lab/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagEmbedRoute = ApiRagEmbedRouteImport.update({
  id: '/api/rag/embed',
  path: '/api/rag/embed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/models': typeof ApiModelsRoute
  '/cognitive-lab/$gameId': typeof CognitiveLabGameIdRoute
  '/cognitive-lab/daily': typeof CognitiveLabDailyRoute
  '/cognitive-lab/dashboard': typeof CognitiveLabDashboardRoute
  '/cognitive-lab/': typeof CognitiveLabIndexRoute
  '/api/rag/embed': typeof ApiRagEmbedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/models': typeof ApiModelsRoute
  '/cognitive-lab/$gameId': typeof CognitiveLabGameIdRoute
  '/cognitive-lab/daily': typeof CognitiveLabDailyRoute
  '/cognitive-lab/dashboard': typeof CognitiveLabDashboardRoute
  '/cognitive-lab': typeof CognitiveLabIndexRoute
  '/api/rag/embed': typeof ApiRagEmbedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/models': typeof ApiModelsRoute
  '/cognitive-lab/$gameId': typeof CognitiveLabGameIdRoute
  '/cognitive-lab/daily': typeof CognitiveLabDailyRoute
  '/cognitive-lab/dashboard': typeof CognitiveLabDashboardRoute
  '/cognitive-lab/': typeof CognitiveLabIndexRoute
  '/api/rag/embed': typeof ApiRagEmbedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/models'
    | '/cognitive-lab/$gameId'
    | '/cognitive-lab/daily'
    | '/cognitive-lab/dashboard'
    | '/cognitive-lab/'
    | '/api/rag/embed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/models'
    | '/cognitive-lab/$gameId'
    | '/cognitive-lab/daily'
    | '/cognitive-lab/dashboard'
    | '/cognitive-lab'
    | '/api/rag/embed'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/models'
    | '/cognitive-lab/$gameId'
    | '/cognitive-lab/daily'
    | '/cognitive-lab/dashboard'
    | '/cognitive-lab/'
    | '/api/rag/embed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiModelsRoute: typeof ApiModelsRoute
  CognitiveLabGameIdRoute: typeof CognitiveLabGameIdRoute
  CognitiveLabDailyRoute: typeof CognitiveLabDailyRoute
  CognitiveLabDashboardRoute: typeof CognitiveLabDashboardRoute
  CognitiveLabIndexRoute: typeof CognitiveLabIndexRoute
  ApiRagEmbedRoute: typeof ApiRagEmbedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive-lab/': {
      id: '/cognitive-lab/'
      path: '/cognitive-lab'
      fullPath: '/cognitive-lab/'
      preLoaderRoute: typeof CognitiveLabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive-lab/$gameId': {
      id: '/cognitive-lab/$gameId'
      path: '/cognitive-lab/$gameId'
      fullPath: '/cognitive-lab/$gameId'
      preLoaderRoute: typeof CognitiveLabGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive-lab/daily': {
      id: '/cognitive-lab/daily'
      path: '/cognitive-lab/daily'
      fullPath: '/cognitive-lab/daily'
      preLoaderRoute: typeof CognitiveLabDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive-lab/dashboard': {
      id: '/cognitive-lab/dashboard'
      path: '/cognitive-lab/dashboard'
      fullPath: '/cognitive-lab/dashboard'
      preLoaderRoute: typeof CognitiveLabDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag/embed': {
      id: '/api/rag/embed'
      path: '/api/rag/embed'
      fullPath: '/api/rag/embed'
      preLoaderRoute: typeof ApiRagEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiModelsRoute: ApiModelsRoute,
  CognitiveLabGameIdRoute: CognitiveLabGameIdRoute,
  CognitiveLabDailyRoute: CognitiveLabDailyRoute,
  CognitiveLabDashboardRoute: CognitiveLabDashboardRoute,
  CognitiveLabIndexRoute: CognitiveLabIndexRoute,
  ApiRagEmbedRoute: ApiRagEmbedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
