// ─────────────────────────────────────────────────────────────────────────────
// Pattern Shift — Pattern Recognition Game Engine
// ─────────────────────────────────────────────────────────────────────────────
// Shows a sequence of shapes/colors. Player picks the next element from 4 options.
// Patterns are generated by choosing a rule (color cycle, shape cycle, alternating,
// arithmetic progression, etc.) and building the sequence deterministically.
// ─────────────────────────────────────────────────────────────────────────────

import type { DifficultyLevel } from "../types";

export type PatternColor = "blue" | "red" | "green" | "yellow" | "purple" | "orange";
export type PatternShape = "circle" | "square" | "triangle" | "diamond" | "pentagon";
export type PatternSize = "sm" | "md" | "lg";

export interface PatternItem {
  shape: PatternShape;
  color: PatternColor;
  size: PatternSize;
}

export interface PatternShiftChallenge {
  sequence: PatternItem[];   // shown items (length 4–6)
  answer: PatternItem;       // the correct next item
  options: PatternItem[];    // 4 shuffled options including the answer
  rule: string;              // description of the rule (shown in explanation)
}

const SHAPES: PatternShape[] = ["circle", "square", "triangle", "diamond", "pentagon"];
const COLORS: PatternColor[] = ["blue", "red", "green", "yellow", "purple", "orange"];
const SIZES: PatternSize[] = ["sm", "md", "lg"];

function rotateArray<T>(arr: T[], step: number, index: number): T {
  return arr[index % arr.length] as T;
}

function rand<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)] as T;
}

function randExcept<T>(arr: T[], exclude: T): T {
  const pool = arr.filter((x) => x !== exclude);
  return pool[Math.floor(Math.random() * pool.length)] as T;
}

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    const x = a[i];
    const y = a[j];
    if (x !== undefined && y !== undefined) {
      a[i] = y;
      a[j] = x;
    }
  }
  return a;
}

type RuleType =
  | "color_cycle"
  | "shape_cycle"
  | "alternating_color"
  | "alternating_shape"
  | "size_cycle"
  | "color_shape_cycle"
  | "double_rule";

function buildSequence(rule: RuleType, length: number): { items: PatternItem[]; answer: PatternItem; ruleDesc: string } {
  const baseShape = rand(SHAPES);
  const baseColor = rand(COLORS);
  const baseSize = rand(SIZES);

  // Color cycle
  if (rule === "color_cycle") {
    const startIdx = Math.floor(Math.random() * COLORS.length);
    const items: PatternItem[] = Array.from({ length }, (_, i) => ({
      shape: baseShape,
      color: rotateArray(COLORS, 1, startIdx + i),
      size: baseSize,
    }));
    const answer: PatternItem = {
      shape: baseShape,
      color: rotateArray(COLORS, 1, startIdx + length),
      size: baseSize,
    };
    return { items, answer, ruleDesc: "The color cycles through a fixed sequence." };
  }

  // Shape cycle
  if (rule === "shape_cycle") {
    const startIdx = Math.floor(Math.random() * SHAPES.length);
    const items: PatternItem[] = Array.from({ length }, (_, i) => ({
      shape: rotateArray(SHAPES, 1, startIdx + i),
      color: baseColor,
      size: baseSize,
    }));
    const answer: PatternItem = {
      shape: rotateArray(SHAPES, 1, startIdx + length),
      color: baseColor,
      size: baseSize,
    };
    return { items, answer, ruleDesc: "The shape cycles through a fixed sequence." };
  }

  // Alternating color between 2 colors
  if (rule === "alternating_color") {
    const colorA = rand(COLORS);
    const colorB = randExcept(COLORS, colorA);
    const items: PatternItem[] = Array.from({ length }, (_, i) => ({
      shape: baseShape,
      color: i % 2 === 0 ? colorA : colorB,
      size: baseSize,
    }));
    const answer: PatternItem = {
      shape: baseShape,
      color: length % 2 === 0 ? colorA : colorB,
      size: baseSize,
    };
    return { items, answer, ruleDesc: "The color alternates between two values." };
  }

  // Alternating shape between 2 shapes
  if (rule === "alternating_shape") {
    const shapeA = rand(SHAPES);
    const shapeB = randExcept(SHAPES, shapeA);
    const items: PatternItem[] = Array.from({ length }, (_, i) => ({
      shape: i % 2 === 0 ? shapeA : shapeB,
      color: baseColor,
      size: baseSize,
    }));
    const answer: PatternItem = {
      shape: length % 2 === 0 ? shapeA : shapeB,
      color: baseColor,
      size: baseSize,
    };
    return { items, answer, ruleDesc: "The shape alternates between two values." };
  }

  // Size cycle sm→md→lg→sm→…
  if (rule === "size_cycle") {
    const startIdx = Math.floor(Math.random() * SIZES.length);
    const items: PatternItem[] = Array.from({ length }, (_, i) => ({
      shape: baseShape,
      color: baseColor,
      size: rotateArray(SIZES, 1, startIdx + i),
    }));
    const answer: PatternItem = {
      shape: baseShape,
      color: baseColor,
      size: rotateArray(SIZES, 1, startIdx + length),
    };
    return { items, answer, ruleDesc: "The size cycles through small → medium → large." };
  }

  // Both color and shape cycle simultaneously
  if (rule === "color_shape_cycle") {
    const colorStart = Math.floor(Math.random() * COLORS.length);
    const shapeStart = Math.floor(Math.random() * SHAPES.length);
    const items: PatternItem[] = Array.from({ length }, (_, i) => ({
      shape: rotateArray(SHAPES, 1, shapeStart + i),
      color: rotateArray(COLORS, 1, colorStart + i),
      size: baseSize,
    }));
    const answer: PatternItem = {
      shape: rotateArray(SHAPES, 1, shapeStart + length),
      color: rotateArray(COLORS, 1, colorStart + length),
      size: baseSize,
    };
    return { items, answer, ruleDesc: "Both shape and color cycle simultaneously." };
  }

  // Double rule: color alternates AND shape cycles
  // (difficulty 4–5 only)
  {
    const colorA = rand(COLORS);
    const colorB = randExcept(COLORS, colorA);
    const shapeStart = Math.floor(Math.random() * SHAPES.length);
    const items: PatternItem[] = Array.from({ length }, (_, i) => ({
      shape: rotateArray(SHAPES, 1, shapeStart + i),
      color: i % 2 === 0 ? colorA : colorB,
      size: rotateArray(SIZES, 1, i),
    }));
    const answer: PatternItem = {
      shape: rotateArray(SHAPES, 1, shapeStart + length),
      color: length % 2 === 0 ? colorA : colorB,
      size: rotateArray(SIZES, 1, length),
    };
    return { items, answer, ruleDesc: "Shape cycles, color alternates, and size cycles — three simultaneous rules." };
  }
}

const DIFF_RULES: Record<DifficultyLevel, RuleType[]> = {
  1: ["color_cycle", "shape_cycle", "alternating_color"],
  2: ["color_cycle", "shape_cycle", "alternating_color", "alternating_shape"],
  3: ["alternating_color", "alternating_shape", "size_cycle", "color_shape_cycle"],
  4: ["size_cycle", "color_shape_cycle", "double_rule"],
  5: ["color_shape_cycle", "double_rule"],
};

const DIFF_LENGTH: Record<DifficultyLevel, number> = {
  1: 4,
  2: 4,
  3: 5,
  4: 5,
  5: 6,
};

function makeDistractorItem(answer: PatternItem): PatternItem {
  // Mutate one or two attributes of the answer to create a plausible wrong option
  const mutate = Math.floor(Math.random() * 3);
  if (mutate === 0) return { ...answer, color: randExcept(COLORS, answer.color) };
  if (mutate === 1) return { ...answer, shape: randExcept(SHAPES, answer.shape) };
  return { ...answer, size: randExcept(SIZES, answer.size) };
}

/** Make sure 4 options are distinct */
function makeOptions(answer: PatternItem): PatternItem[] {
  const opts: PatternItem[] = [answer];
  while (opts.length < 4) {
    const d = makeDistractorItem(answer);
    const duplicate = opts.some(
      (o) => o.shape === d.shape && o.color === d.color && o.size === d.size,
    );
    if (!duplicate) opts.push(d);
  }
  return shuffle(opts);
}

export function generatePatternShiftChallenge(difficulty: DifficultyLevel): PatternShiftChallenge {
  const rules = DIFF_RULES[difficulty];
  const rule = rules[Math.floor(Math.random() * rules.length)] as RuleType;
  const length = DIFF_LENGTH[difficulty];

  const { items, answer, ruleDesc } = buildSequence(rule, length);
  const options = makeOptions(answer);

  return { sequence: items, answer, options, rule: ruleDesc };
}

export function validatePatternShiftAnswer(
  challenge: PatternShiftChallenge,
  selected: PatternItem,
): boolean {
  return (
    selected.shape === challenge.answer.shape &&
    selected.color === challenge.answer.color &&
    selected.size === challenge.answer.size
  );
}
