import type { TrustedWebsite } from './web-directory-types';

/**
 * Curated dataset of trusted, official websites organized by category.
 * All URLs point to the real, official domain for each organization.
 */
export const TRUSTED_WEBSITES: TrustedWebsite[] = [
  // Government
  {
    id: 'gov-usa',
    name: 'USA.gov',
    url: 'https://www.usa.gov',
    category: 'Government',
    description: 'Official portal for U.S. federal government services and information.',
    verified: true,
  },
  {
    id: 'gov-whitehouse',
    name: 'The White House',
    url: 'https://www.whitehouse.gov',
    category: 'Government',
    description: 'Official site of the Executive Office of the President of the United States.',
    verified: true,
  },
  {
    id: 'gov-irs',
    name: 'IRS',
    url: 'https://www.irs.gov',
    category: 'Government',
    description: 'Internal Revenue Service, the U.S. federal tax administration agency.',
    verified: true,
  },
  {
    id: 'gov-usps',
    name: 'USPS',
    url: 'https://www.usps.com',
    category: 'Government',
    description: 'United States Postal Service for mail and package shipping.',
    verified: true,
  },
  {
    id: 'gov-nasa',
    name: 'NASA',
    url: 'https://www.nasa.gov',
    category: 'Government',
    description: 'U.S. federal agency responsible for civilian space programs and research.',
    verified: true,
  },

  // Education
  {
    id: 'edu-khan',
    name: 'Khan Academy',
    url: 'https://www.khanacademy.org',
    category: 'Education',
    description: 'Free online courses, lessons, and practice for learners of all ages.',
    verified: true,
  },
  {
    id: 'edu-coursera',
    name: 'Coursera',
    url: 'https://www.coursera.org',
    category: 'Education',
    description: 'Online courses and degrees from universities and companies worldwide.',
    verified: true,
  },
  {
    id: 'edu-edx',
    name: 'edX',
    url: 'https://www.edx.org',
    category: 'Education',
    description: 'Online courses from top universities, including many free options.',
    verified: true,
  },
  {
    id: 'edu-mit',
    name: 'MIT',
    url: 'https://www.mit.edu',
    category: 'Education',
    description: 'Massachusetts Institute of Technology, a leading research university.',
    verified: true,
  },
  {
    id: 'edu-harvard',
    name: 'Harvard University',
    url: 'https://www.harvard.edu',
    category: 'Education',
    description: "One of the world's leading research and teaching universities.",
    verified: true,
  },

  // Developers
  {
    id: 'dev-github',
    name: 'GitHub',
    url: 'https://github.com',
    category: 'Developers',
    description: 'Platform for hosting and collaborating on code using Git.',
    verified: true,
  },
  {
    id: 'dev-stackoverflow',
    name: 'Stack Overflow',
    url: 'https://stackoverflow.com',
    category: 'Developers',
    description: 'Q&A community for programmers and software developers.',
    verified: true,
  },
  {
    id: 'dev-mdn',
    name: 'MDN Web Docs',
    url: 'https://developer.mozilla.org',
    category: 'Developers',
    description: 'Official documentation for web platform technologies, by Mozilla.',
    verified: true,
  },
  {
    id: 'dev-w3schools',
    name: 'W3Schools',
    url: 'https://www.w3schools.com',
    category: 'Developers',
    description: 'Tutorials and references for web development languages.',
    verified: true,
  },
  {
    id: 'dev-npm',
    name: 'npm',
    url: 'https://www.npmjs.com',
    category: 'Developers',
    description: 'Package registry for JavaScript and Node.js libraries.',
    verified: true,
  },

  // AI
  {
    id: 'ai-openai',
    name: 'OpenAI',
    url: 'https://www.openai.com',
    category: 'AI',
    description: 'AI research and deployment company behind ChatGPT and GPT models.',
    verified: true,
  },
  {
    id: 'ai-anthropic',
    name: 'Anthropic',
    url: 'https://www.anthropic.com',
    category: 'AI',
    description: 'AI safety company and creator of the Claude family of models.',
    verified: true,
  },
  {
    id: 'ai-deepmind',
    name: 'Google DeepMind',
    url: 'https://deepmind.google',
    category: 'AI',
    description: "Google's AI research lab focused on advancing artificial intelligence.",
    verified: true,
  },
  {
    id: 'ai-huggingface',
    name: 'Hugging Face',
    url: 'https://huggingface.co',
    category: 'AI',
    description: 'Platform and community for machine learning models and datasets.',
    verified: true,
  },
  {
    id: 'ai-microsoft',
    name: 'Microsoft AI',
    url: 'https://www.microsoft.com/en-us/ai',
    category: 'AI',
    description: "Microsoft's hub for its AI products, research, and tools.",
    verified: true,
  },

  // Social Media
  {
    id: 'social-facebook',
    name: 'Facebook',
    url: 'https://www.facebook.com',
    category: 'Social Media',
    description: 'Social networking platform for connecting with friends and communities.',
    verified: true,
  },
  {
    id: 'social-x',
    name: 'X (Twitter)',
    url: 'https://x.com',
    category: 'Social Media',
    description: 'Real-time social media platform for short-form posts and discussion.',
    verified: true,
  },
  {
    id: 'social-instagram',
    name: 'Instagram',
    url: 'https://www.instagram.com',
    category: 'Social Media',
    description: 'Photo and video sharing social networking platform.',
    verified: true,
  },
  {
    id: 'social-linkedin',
    name: 'LinkedIn',
    url: 'https://www.linkedin.com',
    category: 'Social Media',
    description: 'Professional networking platform for careers and business.',
    verified: true,
  },
  {
    id: 'social-reddit',
    name: 'Reddit',
    url: 'https://www.reddit.com',
    category: 'Social Media',
    description: 'Network of communities for discussion on nearly any topic.',
    verified: true,
  },

  // Cloud
  {
    id: 'cloud-aws',
    name: 'Amazon Web Services',
    url: 'https://aws.amazon.com',
    category: 'Cloud',
    description: "Amazon's cloud computing platform offering infrastructure and services.",
    verified: true,
  },
  {
    id: 'cloud-gcp',
    name: 'Google Cloud',
    url: 'https://cloud.google.com',
    category: 'Cloud',
    description: "Google's suite of cloud computing services.",
    verified: true,
  },
  {
    id: 'cloud-azure',
    name: 'Microsoft Azure',
    url: 'https://azure.microsoft.com',
    category: 'Cloud',
    description: "Microsoft's cloud computing platform and services.",
    verified: true,
  },
  {
    id: 'cloud-cloudflare',
    name: 'Cloudflare',
    url: 'https://www.cloudflare.com',
    category: 'Cloud',
    description: 'Web infrastructure and security company providing CDN and DNS services.',
    verified: true,
  },
  {
    id: 'cloud-digitalocean',
    name: 'DigitalOcean',
    url: 'https://www.digitalocean.com',
    category: 'Cloud',
    description: 'Cloud hosting platform aimed at developers and small businesses.',
    verified: true,
  },

  // Payments
  {
    id: 'pay-paypal',
    name: 'PayPal',
    url: 'https://www.paypal.com',
    category: 'Payments',
    description: 'Online payment platform for sending and receiving money.',
    verified: true,
  },
  {
    id: 'pay-stripe',
    name: 'Stripe',
    url: 'https://stripe.com',
    category: 'Payments',
    description: 'Payment processing platform for internet businesses.',
    verified: true,
  },
  {
    id: 'pay-venmo',
    name: 'Venmo',
    url: 'https://venmo.com',
    category: 'Payments',
    description: 'Mobile payment service for sending money between friends and family.',
    verified: true,
  },
  {
    id: 'pay-wise',
    name: 'Wise',
    url: 'https://wise.com',
    category: 'Payments',
    description: 'International money transfer service with low-cost currency exchange.',
    verified: true,
  },
  {
    id: 'pay-square',
    name: 'Square',
    url: 'https://squareup.com',
    category: 'Payments',
    description: 'Payment processing and point-of-sale tools for businesses.',
    verified: true,
  },

  // News
  {
    id: 'news-bbc',
    name: 'BBC News',
    url: 'https://www.bbc.com/news',
    category: 'News',
    description: 'International news coverage from the British Broadcasting Corporation.',
    verified: true,
  },
  {
    id: 'news-reuters',
    name: 'Reuters',
    url: 'https://www.reuters.com',
    category: 'News',
    description: 'Global news organization known for wire-service reporting.',
    verified: true,
  },
  {
    id: 'news-ap',
    name: 'Associated Press',
    url: 'https://apnews.com',
    category: 'News',
    description: 'Nonprofit news cooperative providing global news coverage.',
    verified: true,
  },
  {
    id: 'news-nytimes',
    name: 'The New York Times',
    url: 'https://www.nytimes.com',
    category: 'News',
    description: 'American daily newspaper with domestic and international coverage.',
    verified: true,
  },
  {
    id: 'news-npr',
    name: 'NPR',
    url: 'https://www.npr.org',
    category: 'News',
    description: 'Nonprofit American media organization providing news and cultural coverage.',
    verified: true,
  },

  // Cyber Security
  {
    id: 'sec-cisa',
    name: 'CISA',
    url: 'https://www.cisa.gov',
    category: 'Cyber Security',
    description: 'U.S. Cybersecurity and Infrastructure Security Agency.',
    verified: true,
  },
  {
    id: 'sec-hibp',
    name: 'Have I Been Pwned',
    url: 'https://haveibeenpwned.com',
    category: 'Cyber Security',
    description: 'Service to check if your email or accounts appear in data breaches.',
    verified: true,
  },
  {
    id: 'sec-virustotal',
    name: 'VirusTotal',
    url: 'https://www.virustotal.com',
    category: 'Cyber Security',
    description: 'Analyzes files and URLs for viruses, worms, and other malware.',
    verified: true,
  },
  {
    id: 'sec-owasp',
    name: 'OWASP',
    url: 'https://owasp.org',
    category: 'Cyber Security',
    description: 'Nonprofit foundation focused on improving software security.',
    verified: true,
  },
  {
    id: 'sec-krebs',
    name: 'Krebs on Security',
    url: 'https://krebsonsecurity.com',
    category: 'Cyber Security',
    description: 'In-depth security news and investigation by journalist Brian Krebs.',
    verified: true,
  },

  // Shopping
  {
    id: 'shop-amazon',
    name: 'Amazon',
    url: 'https://www.amazon.com',
    category: 'Shopping',
    description: 'Online marketplace offering a wide range of products.',
    verified: true,
  },
  {
    id: 'shop-ebay',
    name: 'eBay',
    url: 'https://www.ebay.com',
    category: 'Shopping',
    description: 'Online marketplace for auctions and direct purchases.',
    verified: true,
  },
  {
    id: 'shop-etsy',
    name: 'Etsy',
    url: 'https://www.etsy.com',
    category: 'Shopping',
    description: 'Marketplace for handmade, vintage, and craft goods.',
    verified: true,
  },
  {
    id: 'shop-walmart',
    name: 'Walmart',
    url: 'https://www.walmart.com',
    category: 'Shopping',
    description: 'Retail corporation offering groceries and general merchandise online.',
    verified: true,
  },
  {
    id: 'shop-target',
    name: 'Target',
    url: 'https://www.target.com',
    category: 'Shopping',
    description: 'American retail chain offering a broad range of products online.',
    verified: true,
  },

  // Entertainment
  {
    id: 'ent-netflix',
    name: 'Netflix',
    url: 'https://www.netflix.com',
    category: 'Entertainment',
    description: 'Streaming service for movies, TV shows, and original content.',
    verified: true,
  },
  {
    id: 'ent-youtube',
    name: 'YouTube',
    url: 'https://www.youtube.com',
    category: 'Entertainment',
    description: 'Video sharing platform for a wide range of content.',
    verified: true,
  },
  {
    id: 'ent-spotify',
    name: 'Spotify',
    url: 'https://www.spotify.com',
    category: 'Entertainment',
    description: 'Music and podcast streaming service.',
    verified: true,
  },
  {
    id: 'ent-disneyplus',
    name: 'Disney+',
    url: 'https://www.disneyplus.com',
    category: 'Entertainment',
    description: 'Streaming service for Disney, Pixar, Marvel, and Star Wars content.',
    verified: true,
  },
  {
    id: 'ent-twitch',
    name: 'Twitch',
    url: 'https://www.twitch.tv',
    category: 'Entertainment',
    description: 'Live streaming platform focused on gaming and creative content.',
    verified: true,
  },

  // Sports
  {
    id: 'sport-espn',
    name: 'ESPN',
    url: 'https://www.espn.com',
    category: 'Sports',
    description: 'Sports news, scores, and coverage across many leagues.',
    verified: true,
  },
  {
    id: 'sport-nba',
    name: 'NBA',
    url: 'https://www.nba.com',
    category: 'Sports',
    description: 'Official site of the National Basketball Association.',
    verified: true,
  },
  {
    id: 'sport-nfl',
    name: 'NFL',
    url: 'https://www.nfl.com',
    category: 'Sports',
    description: 'Official site of the National Football League.',
    verified: true,
  },
  {
    id: 'sport-fifa',
    name: 'FIFA',
    url: 'https://www.fifa.com',
    category: 'Sports',
    description: 'Governing body of international football (soccer).',
    verified: true,
  },
  {
    id: 'sport-olympics',
    name: 'Olympics',
    url: 'https://www.olympics.com',
    category: 'Sports',
    description: 'Official site of the International Olympic Committee.',
    verified: true,
  },

  // Travel
  {
    id: 'travel-booking',
    name: 'Booking.com',
    url: 'https://www.booking.com',
    category: 'Travel',
    description: 'Online travel agency for hotel and accommodation bookings.',
    verified: true,
  },
  {
    id: 'travel-airbnb',
    name: 'Airbnb',
    url: 'https://www.airbnb.com',
    category: 'Travel',
    description: 'Marketplace for lodging, homestays, and travel experiences.',
    verified: true,
  },
  {
    id: 'travel-expedia',
    name: 'Expedia',
    url: 'https://www.expedia.com',
    category: 'Travel',
    description: 'Online travel booking site for flights, hotels, and packages.',
    verified: true,
  },
  {
    id: 'travel-tripadvisor',
    name: 'Tripadvisor',
    url: 'https://www.tripadvisor.com',
    category: 'Travel',
    description: 'Travel platform for reviews of hotels, restaurants, and attractions.',
    verified: true,
  },
  {
    id: 'travel-googleflights',
    name: 'Google Flights',
    url: 'https://www.google.com/travel/flights',
    category: 'Travel',
    description: 'Flight search tool for comparing prices and schedules.',
    verified: true,
  },

  // Health
  {
    id: 'health-who',
    name: 'World Health Organization',
    url: 'https://www.who.int',
    category: 'Health',
    description: 'United Nations agency responsible for international public health.',
    verified: true,
  },
  {
    id: 'health-cdc',
    name: 'CDC',
    url: 'https://www.cdc.gov',
    category: 'Health',
    description: 'U.S. Centers for Disease Control and Prevention.',
    verified: true,
  },
  {
    id: 'health-nih',
    name: 'NIH',
    url: 'https://www.nih.gov',
    category: 'Health',
    description: "U.S. National Institutes of Health, the nation's medical research agency.",
    verified: true,
  },
  {
    id: 'health-mayoclinic',
    name: 'Mayo Clinic',
    url: 'https://www.mayoclinic.org',
    category: 'Health',
    description: 'Nonprofit medical center providing trusted health information.',
    verified: true,
  },
  {
    id: 'health-webmd',
    name: 'WebMD',
    url: 'https://www.webmd.com',
    category: 'Health',
    description: 'Health information and medical reference site.',
    verified: true,
  },

  // Productivity
  {
    id: 'prod-notion',
    name: 'Notion',
    url: 'https://www.notion.so',
    category: 'Productivity',
    description: 'All-in-one workspace for notes, docs, and project management.',
    verified: true,
  },
  {
    id: 'prod-trello',
    name: 'Trello',
    url: 'https://trello.com',
    category: 'Productivity',
    description: 'Visual project management tool based on boards and cards.',
    verified: true,
  },
  {
    id: 'prod-asana',
    name: 'Asana',
    url: 'https://asana.com',
    category: 'Productivity',
    description: 'Work management platform for teams to track projects and tasks.',
    verified: true,
  },
  {
    id: 'prod-todoist',
    name: 'Todoist',
    url: 'https://todoist.com',
    category: 'Productivity',
    description: 'Task manager and to-do list app for organizing work and life.',
    verified: true,
  },
  {
    id: 'prod-googlecalendar',
    name: 'Google Calendar',
    url: 'https://calendar.google.com',
    category: 'Productivity',
    description: 'Time-management and scheduling calendar service by Google.',
    verified: true,
  },

  // Design
  {
    id: 'design-figma',
    name: 'Figma',
    url: 'https://www.figma.com',
    category: 'Design',
    description: 'Collaborative interface design and prototyping tool.',
    verified: true,
  },
  {
    id: 'design-adobe',
    name: 'Adobe',
    url: 'https://www.adobe.com',
    category: 'Design',
    description: 'Creative software suite including Photoshop, Illustrator, and more.',
    verified: true,
  },
  {
    id: 'design-dribbble',
    name: 'Dribbble',
    url: 'https://dribbble.com',
    category: 'Design',
    description: 'Community for showcasing and discovering creative design work.',
    verified: true,
  },
  {
    id: 'design-behance',
    name: 'Behance',
    url: 'https://www.behance.net',
    category: 'Design',
    description: "Adobe's platform for showcasing creative portfolios.",
    verified: true,
  },
  {
    id: 'design-canva',
    name: 'Canva',
    url: 'https://www.canva.com',
    category: 'Design',
    description: 'Online design tool for graphics, presentations, and social media content.',
    verified: true,
  },

  // Finance
  {
    id: 'fin-nasdaq',
    name: 'Nasdaq',
    url: 'https://www.nasdaq.com',
    category: 'Finance',
    description: 'Stock market data, listings, and financial news.',
    verified: true,
  },
  {
    id: 'fin-nyse',
    name: 'NYSE',
    url: 'https://www.nyse.com',
    category: 'Finance',
    description: 'New York Stock Exchange, a major global securities exchange.',
    verified: true,
  },
  {
    id: 'fin-bloomberg',
    name: 'Bloomberg',
    url: 'https://www.bloomberg.com',
    category: 'Finance',
    description: 'Global provider of financial news, data, and analysis.',
    verified: true,
  },
  {
    id: 'fin-investopedia',
    name: 'Investopedia',
    url: 'https://www.investopedia.com',
    category: 'Finance',
    description: 'Educational resource for investing and personal finance topics.',
    verified: true,
  },
  {
    id: 'fin-nerdwallet',
    name: 'NerdWallet',
    url: 'https://www.nerdwallet.com',
    category: 'Finance',
    description: 'Personal finance company offering comparison tools and guidance.',
    verified: true,
  },

  // Jobs & Careers
  {
    id: 'jobs-indeed',
    name: 'Indeed',
    url: 'https://www.indeed.com',
    category: 'Jobs & Careers',
    description: 'Job search engine aggregating listings from across the web.',
    verified: true,
  },
  {
    id: 'jobs-glassdoor',
    name: 'Glassdoor',
    url: 'https://www.glassdoor.com',
    category: 'Jobs & Careers',
    description: 'Job listings alongside company reviews and salary insights.',
    verified: true,
  },
  {
    id: 'jobs-monster',
    name: 'Monster',
    url: 'https://www.monster.com',
    category: 'Jobs & Careers',
    description: 'Job search platform connecting employers and job seekers.',
    verified: true,
  },
  {
    id: 'jobs-ziprecruiter',
    name: 'ZipRecruiter',
    url: 'https://www.ziprecruiter.com',
    category: 'Jobs & Careers',
    description: 'Online employment marketplace for job seekers and employers.',
    verified: true,
  },
  {
    id: 'jobs-usajobs',
    name: 'USAJOBS',
    url: 'https://www.usajobs.gov',
    category: 'Jobs & Careers',
    description: 'Official job site of the United States federal government.',
    verified: true,
  },

  // Communication
  {
    id: 'comm-gmail',
    name: 'Gmail',
    url: 'https://mail.google.com',
    category: 'Communication',
    description: "Google's free email service.",
    verified: true,
  },
  {
    id: 'comm-zoom',
    name: 'Zoom',
    url: 'https://zoom.us',
    category: 'Communication',
    description: 'Video conferencing and online meeting platform.',
    verified: true,
  },
  {
    id: 'comm-whatsapp',
    name: 'WhatsApp',
    url: 'https://www.whatsapp.com',
    category: 'Communication',
    description: 'Messaging app for text, voice, and video communication.',
    verified: true,
  },
  {
    id: 'comm-discord',
    name: 'Discord',
    url: 'https://discord.com',
    category: 'Communication',
    description: 'Voice, video, and text chat platform for communities.',
    verified: true,
  },
  {
    id: 'comm-telegram',
    name: 'Telegram',
    url: 'https://telegram.org',
    category: 'Communication',
    description: 'Cloud-based instant messaging and voice-over-IP service.',
    verified: true,
  },

  // Research
  {
    id: 'research-scholar',
    name: 'Google Scholar',
    url: 'https://scholar.google.com',
    category: 'Research',
    description: 'Search engine for scholarly literature across disciplines.',
    verified: true,
  },
  {
    id: 'research-jstor',
    name: 'JSTOR',
    url: 'https://www.jstor.org',
    category: 'Research',
    description: 'Digital library of academic journals, books, and primary sources.',
    verified: true,
  },
  {
    id: 'research-arxiv',
    name: 'arXiv',
    url: 'https://arxiv.org',
    category: 'Research',
    description: 'Open-access repository of preprints in physics, math, CS, and more.',
    verified: true,
  },
  {
    id: 'research-pubmed',
    name: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov',
    category: 'Research',
    description: 'Free search engine for biomedical and life sciences literature.',
    verified: true,
  },
  {
    id: 'research-sciencedirect',
    name: 'ScienceDirect',
    url: 'https://www.sciencedirect.com',
    category: 'Research',
    description: 'Database of scientific and medical research publications.',
    verified: true,
  },

  // Open Source
  {
    id: 'oss-gitlab',
    name: 'GitLab',
    url: 'https://about.gitlab.com',
    category: 'Open Source',
    description: 'DevOps platform with source code hosting and CI/CD tools.',
    verified: true,
  },
  {
    id: 'oss-opensource',
    name: 'Open Source Initiative',
    url: 'https://opensource.org',
    category: 'Open Source',
    description: 'Nonprofit organization that maintains the Open Source Definition.',
    verified: true,
  },
  {
    id: 'oss-apache',
    name: 'Apache Software Foundation',
    url: 'https://www.apache.org',
    category: 'Open Source',
    description:
      'Nonprofit supporting open source software projects, including Apache HTTP Server.',
    verified: true,
  },
  {
    id: 'oss-linuxfoundation',
    name: 'Linux Foundation',
    url: 'https://www.linuxfoundation.org',
    category: 'Open Source',
    description: 'Nonprofit supporting the Linux kernel and other open source projects.',
    verified: true,
  },
  {
    id: 'oss-sourceforge',
    name: 'SourceForge',
    url: 'https://sourceforge.net',
    category: 'Open Source',
    description: 'Web-based platform for hosting and distributing open source software.',
    verified: true,
  },
];
