import React from 'react';
import { Sparkles, TrendingUp, Lightbulb, Zap } from 'lucide-react';

export const AIInsightsPage: React.FC = () => {
  return (
    <div className="mx-auto max-w-7xl space-y-6 p-6">
      <div className="border-b border-[#192032] pb-5">
        <h1 className="flex items-center gap-2.5 text-2xl font-bold tracking-tight text-white">
          <Sparkles className="h-6 w-6 text-purple-400" />
          AI Insights & Analytics
        </h1>
        <p className="mt-1 text-sm text-slate-400">
          Automated recommendations and pattern analysis generated by Aether AI.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-5 md:grid-cols-3">
        <div className="space-y-3 rounded-2xl border border-[#192032] bg-[#0D121F] p-5">
          <div className="w-fit rounded-xl bg-purple-500/10 p-2.5 text-purple-400">
            <TrendingUp className="h-5 w-5" />
          </div>
          <h3 className="text-base font-semibold text-white">Peak Focus Time</h3>
          <p className="text-xs text-slate-400">
            You are 40% more productive between 9:00 AM - 11:30 AM. Block calendar slots for deep
            work.
          </p>
        </div>

        <div className="space-y-3 rounded-2xl border border-[#192032] bg-[#0D121F] p-5">
          <div className="w-fit rounded-xl bg-blue-500/10 p-2.5 text-blue-400">
            <Lightbulb className="h-5 w-5" />
          </div>
          <h3 className="text-base font-semibold text-white">Task Bottlenecks</h3>
          <p className="text-xs text-slate-400">
            3 backend integration tasks are pending code review. Reassigning 1 reviewer will speed
            up velocity.
          </p>
        </div>

        <div className="space-y-3 rounded-2xl border border-[#192032] bg-[#0D121F] p-5">
          <div className="w-fit rounded-xl bg-emerald-500/10 p-2.5 text-emerald-400">
            <Zap className="h-5 w-5" />
          </div>
          <h3 className="text-base font-semibold text-white">Workflow Automation</h3>
          <p className="text-xs text-slate-400">
            Repeated manual file export detected. Enable automated webhook sync to save ~2.5 hrs
            weekly.
          </p>
        </div>
      </div>
    </div>
  );
};
