import React from 'react';
import { Sparkles, TrendingUp, Lightbulb, Zap } from 'lucide-react';

export const AIInsightsPage: React.FC = () => {
  return (
    <div className="p-6 space-y-6 max-w-7xl mx-auto">
      <div className="border-b border-[#192032] pb-5">
        <h1 className="text-2xl font-bold tracking-tight text-white flex items-center gap-2.5">
          <Sparkles className="w-6 h-6 text-purple-400" />
          AI Insights & Analytics
        </h1>
        <p className="text-sm text-slate-400 mt-1">
          Automated recommendations and pattern analysis generated by Aether AI.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
        <div className="bg-[#0D121F] border border-[#192032] rounded-2xl p-5 space-y-3">
          <div className="p-2.5 rounded-xl bg-purple-500/10 text-purple-400 w-fit">
            <TrendingUp className="w-5 h-5" />
          </div>
          <h3 className="text-base font-semibold text-white">Peak Focus Time</h3>
          <p className="text-xs text-slate-400">
            You are 40% more productive between 9:00 AM - 11:30 AM. Block calendar slots for deep work.
          </p>
        </div>

        <div className="bg-[#0D121F] border border-[#192032] rounded-2xl p-5 space-y-3">
          <div className="p-2.5 rounded-xl bg-blue-500/10 text-blue-400 w-fit">
            <Lightbulb className="w-5 h-5" />
          </div>
          <h3 className="text-base font-semibold text-white">Task Bottlenecks</h3>
          <p className="text-xs text-slate-400">
            3 backend integration tasks are pending code review. Reassigning 1 reviewer will speed up velocity.
          </p>
        </div>

        <div className="bg-[#0D121F] border border-[#192032] rounded-2xl p-5 space-y-3">
          <div className="p-2.5 rounded-xl bg-emerald-500/10 text-emerald-400 w-fit">
            <Zap className="w-5 h-5" />
          </div>
          <h3 className="text-base font-semibold text-white">Workflow Automation</h3>
          <p className="text-xs text-slate-400">
            Repeated manual file export detected. Enable automated webhook sync to save ~2.5 hrs weekly.
          </p>
        </div>
      </div>
    </div>
  );
};
